### ISSUE TITLE
Logovanje uspesnih i neuspesnih autentifikacija / autorizacija

### ISSUE THREAD

**Issue by odbeast** [mldmarko/blok2#4]
Napraviti logovanje uspesnih i neuspesnih autentifikacija pomocu WindowsEventLog.

**Comment by djordjepekic** [comment]
Uglavnom urađeno, naravno potrebano je napraviti autentifikaciju i autorizaciju da bi smisleno mogle da se pozivaju metode za logovanje. Takođe,
NAPOMENA: VS treba biti pokrenut kao administrator da bi smo mogli da pišemo u Windows Event log.
